# Generated by Django 4.0.2 on 2022-02-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bankaccounttype_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
